version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: indusgram
      POSTGRES_USER: indusgram_user
      POSTGRES_PASSWORD: C0JYYPOTlTOHi6vOzxT5DQc8oJyORvbv
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/indusgram
      SPRING_DATASOURCE_USERNAME: indusgram_user
      SPRING_DATASOURCE_PASSWORD: C0JYYPOTlTOHi6vOzxT5DQc8oJyORvbv
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
